let NamePerson1 = "Maxwell Wright";
let NamePerson2 = "Raja Villarreal";
let NamePerson3 = "Helen Richards";
let PhonePerson1 = "(0191) 719 6495";
let PhonePerson2 = "0866 398 2895";
let PhonePerson3 = "0800 1111";
let EmailPerson1 = "Curabitur.egestas.nunc@nonummyac.co.uk";
let EmailPerson2 = "posuere.vulputate@sed.com";
let EmailPerson3 = "libero@convallis.edu";
console.log("DATOS DEL PERSONAL:");
console.log("Persona1:");
console.log("NAME: ", NamePerson1+"; ", "PHONE: ", PhonePerson1+"; ", "EMAIL: ", EmailPerson1);
console.log("Persona3:");
console.log("NAME: ", NamePerson3+"; ", "PHONE: ", PhonePerson3+"; ", "EMAIL: ", EmailPerson3);